import { Container } from '@/shared/uikit/Container';

export const Main: React.FC = () => {
  return (
    <section className="pt-[100px] max-sm:pt-[50px] relative z-[9999]">
      <Container>
        <h1 className="font-[500] text-[80px] leading-[120%] mb-[30px] max-sm:text-[40px] max-sm:mb-[16px]">
          Numbers Strategy
        </h1>
        <p className="font-[500] text-[20px] text-[#B4B4B5] leading-[30px] max-w-[650px] max-sm:text-[14px] max-sm:leading-[20px]">
          The protocol will automatically buy and list floor Telegram Numbers for a profit, using
          the trading fees generated by the token.
        </p>
      </Container>
    </section>
  );
};
