import type { Metadata } from 'next';
import '../globals.css';
import { Header } from '@/widgets/header/Header';
import { Footer } from '@/widgets/footer/Footer';
import { QueryProvider } from '@/shared/api/QueryProvider';

export const metadata: Metadata = {
  title: 'Numbers Strategy',
  description:
    'The protocol will automatically buy and list floor Telegram Numbers for a profit, using the trading fees generated by the token.',
  openGraph: {
    title: 'Numbers Strategy',
    description:
      'The protocol will automatically buy and list floor Telegram Numbers for a profit, using the trading fees generated by the token.',
    url: 'https://comfy-frangipane-d7abb3.netlify.app/',
    siteName: '888 Strategy',
    images: [
      {
        url: 'https://comfy-frangipane-d7abb3.netlify.app/Banner.png',
        width: 1200,
        height: 630,
        alt: 'Numbers Strategy Banner',
      },
    ],
    locale: 'en_US',
    type: 'website',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Numbers Strategy',
    description:
      'The protocol will automatically buy and list floor Telegram Numbers for a profit, using the trading fees generated by the token.',
    images: ['https://comfy-frangipane-d7abb3.netlify.app/Banner.png'],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <QueryProvider>
        <div className="overflow-hidden relative">
          <Header />
          <body className={`antialiased`}>
            <main>{children}</main>
          </body>
          <Footer />
        </div>
      </QueryProvider>
    </html>
  );
}
